defaults: &defaults
  application:
    name: "Insiemento"
    version: "0.59.1"
    updated_at: "15/09/2020"
    started_at: "13/01/2020"
    commercial:
      brand: "Insiemento"
      support_phone: "+39 02 12345678"
      url: "https://www.insiemento.com"
      email: "info@insiemento.com"
      support_email: "support@insiemento.com"
      sender_email: "please-do-not-reply@insiemento.com"
      address: "Via Dostoevskij San Giuliano Milanese (MI)"
      ceo: "Marco Mastrodonato"
      twitter_account: ""
      image: "logo_200.png"
  domains: ["insiemento.local", "localhost"]
  smtp:
    host: "smtp.mailtrap.io"
    domain: "smtp.mailtrap.io"
    port: "2525"
    authentication: :cram_md5
    user: <%= Rails.application.credentials.smtp.dig(:test, :user) %>
    password: <%= Rails.application.credentials.smtp.dig(:test, :password) %>
  sendgrid:
    apipath: https://api.sendgrid.com/v3
  analytics:
    tag: <%= Rails.application.credentials.analytics.dig(:tag) %>
  authentication:
    customer:
      jwt_expiration_hours: 24
  otpservice:
    host: "http://localhost:3033"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  sms:
    provider: "twilio"
    twilio:
      username: <%= Rails.application.credentials.sms.dig(:production, :twilio, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:production, :twilio, :password) %>
    skebby:
      username: <%= Rails.application.credentials.sms.dig(:production, :skebby, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:production, :skebby, :password) %>
    from: "Insiemento"
  smtp:
    host: "smtp.sendgrid.net"
    port: "587"
    user: <%= Rails.application.credentials.smtp.dig(:production, :user) %>
    password: <%= Rails.application.credentials.smtp.dig(:production, :password) %>
    authentication: :plain
    enable_starttls_auto: true
  domains: ["insiemento.com", "herokuapp.com"]
  otpservice:
    host: "https://otpservice.io"