defaults: &defaults
  application:
    name: "Insiemento"
    version: "0.15.0"
    updated_at: "11/04/2020"
    started_at: "13/01/2020"
    host: "insiemento.io"
  sms:
    provider: "twilio"
    twilio:
      username: <%= Rails.application.credentials.sms.dig(:test, :twilio, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:test, :twilio, :password) %>
    skebby:
      username: <%= Rails.application.credentials.sms.dig(:test, :skebby, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:test, :skebby, :password) %>
    from: "Insiemento"
  smtp:
    host: "smtp.mailtrap.io"
    domain: "smtp.mailtrap.io"
    port: "2525"
    authentication: :cram_md5
    user: <%= Rails.application.credentials.smtp.dig(:test, :user) %>
    password: <%= Rails.application.credentials.smtp.dig(:test, :password) %>
  sendgrid:
    apipath: https://api.sendgrid.com/v3
  authentication:
    customer:
      jwt_expiration_hours: 24

development:
  <<: *defaults

test:
  <<: *defaults
  customer_dossier_url: http://localhost/admin/reservations/#{customer_dossier_id}/checkin_contracts

production:
  <<: *defaults
  sms:
    provider: "twilio"
    twilio:
      username: <%= Rails.application.credentials.sms.dig(:production, :twilio, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:production, :twilio, :password) %>
    skebby:
      username: <%= Rails.application.credentials.sms.dig(:production, :skebby, :username) %>
      password: <%= Rails.application.credentials.sms.dig(:production, :skebby, :password) %>
    from: "Insiemento"
  smtp:
    host: "smtp.sendgrid.net"
    port: "587"
    domain: "set_your_domain"
    authentication: :plain
    enable_starttls_auto: true
    user: <%= Rails.application.credentials.smtp.dig(:production, :user) %>
    password: <%= Rails.application.credentials.smtp.dig(:production, :password) %>