# .---------------- [m]inute: (0 - 59)
# |  .------------- [h]our: (0 - 23)
# |  |  .---------- [d]ay of month: (1 - 31)
# |  |  |  .------- [mon]th: (1 - 12) OR jan,feb,mar,apr...
# |  |  |  |  .---- [w]eek day: (0 - 6) (sunday=0 or 7)  OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  *
update_course_events:
  cron: "1,16,31,46 12-22 * * *"
  class: UpdateCourseEventsJob
  queue: course_events
user_documents_manager:
  cron: "0 0,9,11,13,14,15,18,19,20,21,22,23 * * *"
  class: UserDocumentsManagerJob
  queue: user_documents
create_course_events:
  cron: "30 12 * * 6"
  class: ScheduleJob
  queue: course_events
update_subscriptions:
  cron: "6 0 * * *"
  class: UpdateSubscriptionsJob
  queue: users
update_users:
  cron: "9 0 * * 0"
  class: UpdateUsersJob
  queue: users
news:
  cron: "18 0 * * *"
  class: UpdateNewsJob
  queue: news
user_penalties:
  cron: "25 0 * * *"
  class: UserPenaltyJob
  queue: users
