---
:concurrency: 1
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [insiemento_mailer, 1]
  - [course_events, 1]
  - [user_documents, 1]
  - [users, 1]
  - [active_storage_analysis, 1]
